### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by dnp33** [MattShannon/bandmat#3]
Hi Matt,

I tried installing your module but it would not compile unless I removed the compiler argument '-Wno-unused-but-set-variable'. Thanks for writing this package, it's quite useful!

David Purschke
--
PhD Candidate, 
U. of Alberta,
Dep. of Physics

**Comment by MattShannon** [comment]
Hi David, sorry for the slow reply! Hmm, doesn't that option prevent the compiler complaining about unused variables in the code generated by cython? I would've thought if the code compiles without that compiler argument then it would also compile with the argument. What goes wrong if you compile without changing anything? Which compiler are you using?

**Comment by macarbonneau** [comment]
Hello! Thank you for the package. I have the same issue when I install it on Windows. I can remove the argument also and it works. I would suggest that you remove it from the distributed version because other package use it as a dependency and installation fails because of it. 

I'm using Visual studio 14.0      The error is invalid numeric argument.

**Comment by r9y9** [comment]
This should be fixed by #6.

**Comment by MattShannon** [comment]
Windows builds should be fixed now. Please let me know if you experience any further issues.
